WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
EOL = _{ ";" }
NEWLINE = _{ "\n" | "\r\n" }
COMMENT = _{
    "//" ~
    (!NEWLINE ~ ANY)*
}
KeywordBoundary = _{ !(ASCII_ALPHANUMERIC | "_") }

Program = {
    SOI ~
    Statement* ~
    EOI
}

// Keywords
Keyword = {
    KeywordFn |
    KeywordLet |
    KeywordReturn |
    KeywordStruct |
    KeywordImpl |
    KeywordIf |
    KeywordElse |
    KeywordTrue |
    KeywordFalse |
    KeywordWhile |
    KeywordBreak |
    KeywordSelf
}

KeywordFn = @{ "fn" ~ KeywordBoundary }
KeywordLet = @{ "let" ~ KeywordBoundary }
KeywordReturn = @{ "return" ~ KeywordBoundary }
KeywordStruct = @{ "struct" ~ KeywordBoundary }
KeywordImpl = @{ "impl" ~ KeywordBoundary }
KeywordIf = @{ "if" ~ KeywordBoundary }
KeywordElse = @{ "else" ~ KeywordBoundary }
KeywordTrue  = @{ "true" ~ KeywordBoundary }
KeywordFalse = @{ "false" ~ KeywordBoundary }
KeywordWhile = @{ "while" ~ KeywordBoundary }
KeywordLoop = @{ "loop" ~ KeywordBoundary }
KeywordBreak = @{ "break" ~ KeywordBoundary }
KeywordSelf = @{ "self" ~ KeywordBoundary }
KeywordPad = @{ "pad" ~ KeywordBoundary }

// Execution
Block = {
    LBrace ~
        Statement* ~
    RBrace
}

FunctionDefinition = {
    Attribute* ~
    KeywordFn ~ Identifier ~ LParen ~ ParameterList? ~ RParen ~ Block
}

FunctionCall = {
    QualifiedIdentifier ~ GenericArguments? ~ LParen ~ ArgumentList? ~ RParen
}

GenericArguments = {
    "<" ~ DataType ~ (Comma ~ DataType)* ~ ">"
}

ParameterList = { // only allowing our defined data types for now
    Parameter ~ (Comma ~ Parameter)*
}

Parameter = {
    Identifier ~ Colon ~ DataType
}

ArgumentList = {
    Expression ~ (Comma ~ Expression)*
}

// Operators and tokens
Plus            =  { "+" }
Minus           =  { "-" }
Star            =  _{ "*" }
Multiply        =  { "*" } // <- this is explicitly for multiplication and nothing else
Slash           =  { "/" }
Dot             = _{ "." }
Comma           = _{ "," }
Equals          = _{ "=" }
Colon           = _{ ":" }
ScopeResolution = _{ "::" }
LBrace          = _{ "{" }
RBrace          = _{ "}" }
LParen          = _{ "(" }
RParen          = _{ ")" }
LBracket        = _{ "[" }
RBracket        = _{ "]" }
Pound           = _{ "#" }
Hashtag         = _{ Pound }
Ampersand       = _{ "&" }
GreaterThan     = { ">" }
LessThan        = { "<" }
EqualTo         = { "==" }
NotEqualTo      = { "!=" }
GreaterThanOrEqualTo = { ">=" }
LessThanOrEqualTo = { "<=" }

ComparisonOp = _{
    GreaterThanOrEqualTo |
    LessThanOrEqualTo |
    EqualTo |
    NotEqualTo |
    GreaterThan |
    LessThan
}

Identifier = @{
    (ASCII_ALPHA | "_") ~
    (ASCII_ALPHANUMERIC | "_")*
}

QualifiedIdentifier = {
    Identifier ~ (ScopeResolution ~ Identifier)*
}

BuiltinDataType = {
    "u32" | "s32" | "string" | "bool"
}

DataType = {
    ReferenceType |
    BuiltinDataType |
    Identifier
}

ReferenceType = {
    Ampersand ~ DataType
}

TypeAnnotation = {
    Colon ~ DataType
}

Integer = @{
    HexadecimalInteger |
    DecimalInteger
}

Bool = {
    KeywordTrue | KeywordFalse
}

HexadecimalInteger = @{ ("0x" | "0X") ~ ASCII_HEX_DIGIT+ }
DecimalInteger = @{ ASCII_DIGIT+ }

String = @{
    "\"" ~ StringCharacter* ~ "\""
}

StringCharacter = {
    EscapeSequence |
    !("\"" | "\\") ~ ANY
}

EscapeSequence = {
    "\\" ~ (
        "\"" |
        "\\" |
        "n" |
        "r" |
        "t"
    )
}

Value = {
    Bool |
    Integer |
    String |
    Identifier
}

Statement = {
    LoopStatement |
    IfStatement |
    WhileStatement |
    StructImplBlock |
    FunctionDefinition |
    StructDefinition |
    Assignment ~ EOL |
    Return ~ EOL |
    BreakStatement ~ EOL |
    Expression ~ EOL
}

BreakStatement = {
    KeywordBreak
}

LoopStatement = {
    KeywordLoop ~ Block
}

IfStatement = {
    KeywordIf ~ Comparison ~ Block ~ ElseIfStatement* ~ ElseStatement?
}

ElseIfStatement = {
    KeywordElse ~ KeywordIf ~ Comparison ~ Block
}

ElseStatement = {
    KeywordElse ~ Block
}

WhileStatement = {
    KeywordWhile ~ Comparison ~ Block
}

DeclarativeAssignment = {
    KeywordLet ~ Identifier ~ TypeAnnotation? ~ Equals ~ Expression
}

Reassignment = {
    AssignmentTarget ~ Equals ~ Expression
}

AssignmentTarget = {
    Dereference |
    Identifier
}

Assignment = {
    DeclarativeAssignment |
    Reassignment
}

Return = {
    KeywordReturn ~ Expression
}

Expression = {
    Comparison
}

Comparison = {
    Addition ~ (ComparisonOp ~ Addition)*
}

Addition = {
    Multiplication ~ (AddOp ~ Multiplication)*
}

AddOp = _{
    Plus | Minus
}

Multiplication = {
    Unary ~ (MulOp ~ Unary)*
}

MulOp = _{
    Multiply | Slash
}

Unary = {
    Reference |
    Dereference |
    Postfix
}

Reference = {
    Ampersand ~ Unary
}

Dereference = {
    Star ~ Unary
}

Postfix = {
    Atom ~ (PostfixOperation)*
}

PostfixOperation = _{
    MethodCall |
    FieldAccess
}

// distinct from FunctionCall; a method here is a function attached to a struct
MethodCall = {
    Dot ~ Identifier ~ LParen ~ ArgumentList? ~ RParen
}

FieldAccess = {
    Dot ~ Identifier
}

Atom = {
    StructInitialization |
    FunctionCall |
    Value |
    (LParen ~ Expression ~ RParen)
}

StructInitialization = {
    Identifier ~ LBrace ~ StructFieldInitializers? ~ RBrace
}

StructFieldInitializers = {
    StructFieldInitializer ~ (Comma ~ StructFieldInitializer)*
}

StructFieldInitializer = {
    Identifier ~ Colon ~ Expression
}

StructDefinition = {
    Attribute* ~
    KeywordStruct ~ Identifier ~ LBrace ~
        StructMembers? ~
    RBrace
}

StructMembers = {
    StructMember ~ (Comma ~ StructMember)*
}

StructMember = {
    StructFieldDefinition |
    PadDirective
}

PadDirective = {
    KeywordPad ~ LParen ~ Integer ~ RParen
}

StructFieldDefinition = {
    Attribute* ~
    Identifier ~ Colon ~ DataType
}

StructImplBlock = {
    KeywordImpl ~ Identifier ~ LBrace ~
        StructImplDefinitions? ~
    RBrace
}

StructImplDefinitions = {
    (FunctionDefinition | MethodDefinition)*
}

MethodDefinition = {
    Attribute* ~
    KeywordFn ~ Identifier ~ LParen ~ Ampersand ~ KeywordSelf ~ ParameterList? ~ RParen ~ Block
}

Attribute = {
    Hashtag ~
    LBracket ~
    Identifier ~
    AttributeArguments? ~
    RBracket
}

AttributeArguments = {
    LParen ~
    ArgumentList? ~
    RParen
}
