WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
EOL = _{ ";" }
NEWLINE = _{ "\n" | "\r\n" }
COMMENT = _{
    "//" ~
    (!NEWLINE ~ ANY)*
}
KeywordBoundary = _{ !(ASCII_ALPHANUMERIC | "_") }

Program = {
    SOI ~
    Statement* ~
    EOI
}
// Keywords
Keyword = {
    KeywordFn |
    KeywordLet |
    KeywordReturn |
    KeywordStruct |
    KeywordImpl
}

KeywordFn = @{ "fn" ~ KeywordBoundary }
KeywordLet = @{ "let" ~ KeywordBoundary }
KeywordReturn = @{ "return" ~ KeywordBoundary }
KeywordStruct = @{ "struct" ~ KeywordBoundary }
KeywordImpl = @{ "impl" ~ KeywordBoundary }

// Execution
Block = {
    LBrace ~
        Statement* ~
    RBrace
}

FunctionDefinition = {
    KeywordFn ~ Identifier ~ LParen ~ ParameterList? ~ RParen ~ Block
}

FunctionCall = {
    QualifiedIdentifier ~ LParen ~ ArgumentList? ~ RParen
}

ParameterList = { // only allowing our defined data types for now
    Parameter ~ (Comma ~ Parameter)*
}

Parameter = {
    Identifier ~ Colon ~ DataType
}

ArgumentList = {
    Expression ~ (Comma ~ Expression)*
}

// Operators and tokens
Plus   =  { "+" }
Minus  =  { "-" }
Star   =  { "*" }
Slash  =  { "/" }
Dot    = _{ "." }
Comma  = _{ "," }
Equals = _{ "=" }
Colon  = _{ ":" }
ScopeResolution = _{ "::" }
LBrace = _{ "{" }
RBrace = _{ "}" }
LParen = _{ "(" }
RParen = _{ ")" }
LBracket = _{ "[" }
RBracket = _{ "]" }
Pound  = _{ "#" }
Hashtag = _{ Pound }

Identifier = @{
    (ASCII_ALPHA | "_") ~
    (ASCII_ALPHANUMERIC | "_")*
}

QualifiedIdentifier = {
    Identifier ~ (ScopeResolution ~ Identifier)*
}

BuiltinDataType = {
    "u32" | "s32" | "string"
}

DataType = {
    BuiltinDataType |
    Identifier
}

TypeAnnotation = {
    Colon ~ DataType
}

Integer = @{
    HexadecimalInteger |
    DecimalInteger
}

HexadecimalInteger = @{ ("0x" | "0X") ~ ASCII_HEX_DIGIT+ }
DecimalInteger = @{ ASCII_DIGIT+ }

String = @{
    "\"" ~ StringCharacter* ~ "\""
}

StringCharacter = {
    EscapeSequence |
    !("\"" | "\\") ~ ANY
}

EscapeSequence = {
    "\\" ~ (
        "\"" |
        "\\" |
        "n" |
        "r" |
        "t"
    )
}

Value = {
    Identifier |
    Integer |
    String
}

Statement = {
    StructImplBlock |
    FunctionDefinition |
    StructDefinition |
    Assignment ~ EOL |
    Return ~ EOL |
    Expression ~ EOL
}

DeclarativeAssignment = {
    KeywordLet ~ Identifier ~ TypeAnnotation? ~ Equals ~ Expression
}

Reassignment = {
    Identifier ~ Equals ~ Expression
}

Assignment = {
    DeclarativeAssignment |
    Reassignment
}

Return = {
    KeywordReturn ~ Expression
}

Expression = {
    Addition
}

Addition = {
    Multiplication ~ (AddOp ~ Multiplication)*
}

AddOp = _{
    Plus | Minus
}

Multiplication = {
    Unary ~ (MulOp ~ Unary)*
}

MulOp = _{
    Star | Slash
}

Unary = {
    Postfix
}

Postfix = {
    Atom ~ (PostfixOperation)*
}

PostfixOperation = {
    FieldAccess
}

// distinct from FunctionCall; a method here is a function attached to a struct
MethodCall = {
    Dot ~ Identifier ~ LParen ~ ArgumentList? ~ RParen
}

FieldAccess = {
    Dot ~ Identifier
}

Atom = {
    StructInitialization |
    FunctionCall |
    Value |
    LParen ~ Expression ~ RParen
}

StructInitialization = {
    Identifier ~ LBrace ~ StructFieldInitializers? ~ RBrace
}

StructFieldInitializers = {
    StructFieldInitializer ~ (Comma ~ StructFieldInitializer)*
}

StructFieldInitializer = {
    Identifier ~ Colon ~ Expression
}

StructDefinition = {
    KeywordStruct ~ Identifier ~ LBrace ~
        StructFields? ~
    RBrace
}

StructFields = {
    StructFieldDefinition ~ (Comma ~ StructFieldDefinition)*
}

StructFieldDefinition = {
    Identifier ~ Colon ~ DataType
}

StructImplBlock = {
    KeywordImpl ~ Identifier ~ LBrace ~
        FunctionDefinition* ~
    RBrace
}

ConfigStatement = @{
    Hashtag ~ LBracket ~ "configure" ~ LParen ~ String ~ Comma ~ Value ~ RParen ~ RBracket
}
